name: Build and Test

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Start Mongo
              run: sudo docker run -d -p 27017:27017 mongo:3.6

            - uses: actions/checkout@v1
            - name: npm install start and test
              run: |
                  npm install
                  npm start &
                  npm test
